### ISSUE TITLE
Nrepl prematurely closes tcp connection

### ISSUE THREAD

**Issue by mluts** [mluts/ultra-nrepl#1]
Steps to reproduce:
* Start new nrepl using `lein repl`
* `unrepl doc src/myproject/core.clj reduce`

Example exception:
```
ERROR: Unhandled REPL handler exception processing message {:ns whwisdom.core, :op info, :session 3c42f968-1734-4743-8a6a-6e228a87c1b4, :symbol reduce}
java.net.SocketException: Socket closed
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126)
        at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
        at nrepl.bencode$write_netstring_STAR_.invokeStatic(bencode.clj:197)
        at nrepl.bencode$write_netstring_STAR_.invoke(bencode.clj:192)
        at nrepl.bencode$eval13850$fn__13851.invoke(bencode.clj:344)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at nrepl.bencode$eval13877$fn__13878.invoke(bencode.clj:400)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at nrepl.transport$bencode$fn__14025.invoke(transport.clj:117)
        at nrepl.transport.FnTransport.send(transport.clj:41)
        at nrepl.middleware.print$send_nonstreamed.invokeStatic(print.clj:159)
        at nrepl.middleware.print$send_nonstreamed.invoke(print.clj:138)
        at nrepl.middleware.print$printing_transport$reify__14416.send(print.clj:174)
        at nrepl.middleware.caught$caught_transport$reify__14451.send(caught.clj:58)
        at cider.nrepl.middleware.info$handle_info.invokeStatic(info.clj:96)
        at cider.nrepl.middleware.info$handle_info.invoke(info.clj:95)
        at clojure.lang.Var.invoke(Var.java:388)
        at cider.nrepl$wrap_info$fn__15219.invoke(nrepl.clj:181)
        at nrepl.middleware$wrap_conj_descriptor$fn__14203.invoke(middleware.clj:16)
        at cider.nrepl$wrap_ns$fn__15245.invoke(nrepl.clj:263)
        at nrepl.middleware$wrap_conj_descriptor$fn__14203.invoke(middleware.clj:16)
        at cider.nrepl$wrap_profile$fn__15261.invoke(nrepl.clj:306)
        at nrepl.middleware$wrap_conj_descriptor$fn__14203.invoke(middleware.clj:16)
        at cider.nrepl$wrap_debug$fn__15195.invoke(nrepl.clj:137)
        at nrepl.middleware$wrap_conj_descriptor$fn__14203.invoke(middleware.clj:16)
        at cider.nrepl$wrap_enlighten$fn__15203.invoke(nrepl.clj:163)
        at nrepl.middleware$wrap_conj_descriptor$fn__14203.invoke(middleware.clj:16)
        at cider.nrepl$wrap_classpath$fn__15177.invoke(nrepl.clj:111)
        at nrepl.middleware$wrap_conj_descriptor$fn__14203.invoke(middleware.clj:16)
        at cider.nrepl$wrap_slurp$fn__15161.invoke(nrepl.clj:95)
        at nrepl.middleware$wrap_conj_descriptor$fn__14203.invoke(middleware.clj:16)
        at nrepl.middleware.caught$wrap_caught$fn__14460.invoke(caught.clj:97)
        at nrepl.middleware$wrap_conj_descriptor$fn__14203.invoke(middleware.clj:16)
        at nrepl.middleware.print$wrap_print$fn__14427.invoke(print.clj:234)
        at nrepl.middleware$wrap_conj_descriptor$fn__14203.invoke(middleware.clj:16)
        at nrepl.middleware.session$add_stdin$fn__14663.invoke(session.clj:326)
        at nrepl.middleware$wrap_conj_descriptor$fn__14203.invoke(middleware.clj:16)
        at nrepl.middleware.session$session$fn__14648.invoke(session.clj:272)
        at nrepl.middleware$wrap_conj_descriptor$fn__14203.invoke(middleware.clj:16)
        at nrepl.server$handle_STAR_.invokeStatic(server.clj:18)
        at nrepl.server$handle_STAR_.invoke(server.clj:15)
        at nrepl.server$handle$fn__14685.invoke(server.clj:27)
        at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by mluts** [comment]
Issue persists even after i've applied change to open new tcp for each op.
For example `unrepl op describe verbose?=true`
